SCALE = 1
FRAMERATE = 30

VISIBLE_LAYERS_DOWN = 3
VISIBLE_LAYERS_UP = 2

CHEATS = True
MAX_COMMAND_LENGTH = 32
WITCH = False

WINDOW_X = int(1280*SCALE)
WINDOW_Y = int(960*SCALE)
BLOCK_SIZE = int(64*SCALE)
LAYER_Y_OFFSET = int(8*SCALE)
LAYER_X_OFFSET = int(4*SCALE)
LEVEL_COMPLETION_SCALE = 0.25
LEVEL_COMPLETION_OFFSET = int(4*SCALE)
WITCH_FONT_SIZE = int(32*SCALE)
WITCH_FONT_OFFSET = int(8*SCALE)
LEVEL_FONT_SIZE = int(64*SCALE)
LEVEL_FONT_OFFSET = int(16*SCALE)
