SCALE = 1
FRAMERATE = 30
MOVE_LIMIT = 1024

VISIBLE_LAYERS_DOWN = 3
VISIBLE_LAYERS_UP = 2
INVISIBLE_BLOCK_VISIBILITY = 0.02
GRAYNESS = 0.1
THUNDER_PARTICLES = 16

CHEATS = True
PASSWORD_HASH = b'\xd1\xa0\xd9\x07v\xc0\xd4\x1f\x8f@\xb4\t{\x10\xdf[\xf8;\r\n\x7fx=jO\x01\x97T3_\xefK'
MAX_COMMAND_LENGTH = 32
WITCH = True
THREED = False # !! does not quite work
DUDA_CHUJ = False

LOG_INFO = True
LOG_WARNINGS = True
LOG_ERRORS = True

WINDOW_X = int(1280*SCALE)
WINDOW_Y = int(960*SCALE)
BLOCK_SIZE = int(64*SCALE)
LAYER_Y_OFFSET = int(8*SCALE)
LAYER_X_OFFSET = int(4*SCALE)
LEVEL_COMPLETION_SCALE = 0.25
LEVEL_COMPLETION_OFFSET = int(4*SCALE)
WITCH_FONT_SIZE = int(32*SCALE)
WITCH_FONT_OFFSET = int(8*SCALE)
LEVEL_FONT_SIZE = int(64*SCALE)
LEVEL_FONT_OFFSET = int(16*SCALE)
