SCALE = 1
FRAMERATE = 30
MOVE_LIMIT = 1024

VISIBLE_LAYERS_DOWN = 3
VISIBLE_LAYERS_UP = 2
INVISIBLE_BLOCK_VISIBILITY = 0.02
GRAYNESS = 0.1

CHEATS = True
PASSWORD_HASH = b'(M\xc0\x04\x90Y\xaa\xa0\x00!\xb4\xd9\xa5SUj\xd1\xc6\tQ\xf3\xe5\xaf\xbe)\x1f\xb4\xee\xc9Lw\xf0'
MAX_COMMAND_LENGTH = 32
WITCH = False
THREED = False # !! does not quite work
DUDA_CHUJ = False

WINDOW_X = int(1280*SCALE)
WINDOW_Y = int(960*SCALE)
BLOCK_SIZE = int(64*SCALE)
LAYER_Y_OFFSET = int(8*SCALE)
LAYER_X_OFFSET = int(4*SCALE)
LEVEL_COMPLETION_SCALE = 0.25
LEVEL_COMPLETION_OFFSET = int(4*SCALE)
WITCH_FONT_SIZE = int(32*SCALE)
WITCH_FONT_OFFSET = int(8*SCALE)
LEVEL_FONT_SIZE = int(64*SCALE)
LEVEL_FONT_OFFSET = int(16*SCALE)
