
passwords = {
    'null': 1,
    'easyaspie': 2,
    'itbegins': 3,
    'cbgames': 4,
    'thislevelisawasteoftime': 5,
    'longwaytogo': 6,
    'luckyseven': 7,
    'letsjump': 8,
    'invertedcontrolsohmy': 9,
    'gettingtougher': 10,
    'somegenericpassword': 11,
    'numanuma': 12,
    'hello': 13,
    'jumpy': 14,
    'canyouhandleit': 15,
    'theyonlygetharder': 16,
    'thissucks': 17,
    'igiveup': 18,
    'annoyinglyhard': 19,
    'yesitspossible': 20,
}
